# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/flynng/Desktop/ECE491/6lab/6lab.runs/synth_1/.Xil/Vivado-9964-ECE400-F6N3KB2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/sync_input.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/one_bit_ff.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/fsm_psfd.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/fsm_pll.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/fsm_data.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/clkenb_baud.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/clkenb.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/reg_param.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/counter_parm.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/mux8_parm.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/seven_seg.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/f_error.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/FSMs.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/decoder_3_8_en.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/data_buffer.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/counter.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/correlator.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/transmitter_for_mx.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/transmitter.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/p_fifo.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/mx_rcvr.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/fifo_fsm.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/dispctl.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/single_pulser.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/mxtest_2.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/manchester_tx.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6lab.srcs/sources_1/new/ReceiverTestUnit.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6lab.srcs/sources_1/new/TransmitterTestUnit.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/nexys4DDR.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/check_p.sv
      C:/Users/flynng/Desktop/ECE491/6lab/6.srcs/sources/imports/accumulator.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top nexys4DDR
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/flynng/Desktop/ECE491/6lab/6lab.runs/synth_1/.Xil/Vivado-9964-ECE400-F6N3KB2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
