# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.cache/wt} [current_project]
set_property parent.project_path {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sources_1/imports/lab1/reg_param.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sources_1/imports/lab1/mux8_parm.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sources_1/imports/lab1/counter_parm.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sources_1/imports/lab1/clkenb.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sources_1/new/transmitter.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/new/manchester_tx.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sources_1/imports/lab1/nexys4DDR.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/lab2.srcs/sim_1/new/transmitter_bench.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/new/check_p.sv}
  {C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/sources_1/imports/Downloads/mxtest.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/constrs_1/imports/lab1/nexys4DDR.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/flynng/Desktop/ECE491/lab 3/lab 3.srcs/constrs_1/imports/lab1/nexys4DDR.xdc}}]


synth_design -top manchester_tx -part xc7a100tcsg324-1


write_checkpoint -force -noxdef manchester_tx.dcp

catch { report_utilization -file manchester_tx_utilization_synth.rpt -pb manchester_tx_utilization_synth.pb }
