# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -ruleid {1}  -id {Synth 8-3332}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/flynng/Desktop/ECE491/fifo/fifo.cache/wt [current_project]
set_property parent.project_path C:/Users/flynng/Desktop/ECE491/fifo/fifo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/flynng/Desktop/ECE491/fifo/fifo.srcs/sources_1/imports/Downloads/p_fifo.sv
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top p_fifo -part xc7a100tcsg324-1


write_checkpoint -force -noxdef p_fifo.dcp

catch { report_utilization -file p_fifo_utilization_synth.rpt -pb p_fifo_utilization_synth.pb }
